// Datos estáticos de mangas para usar como fallback
const mangasData = [
  {
    id: 1,
    titulo: "One Piece",
    sinopsis: "Monkey D. Luffy se niega a que nadie se interponga en su camino para convertirse en el rey de los piratas. Se embarca en una travesía para encontrar el tesoro One Piece y se une a una tripulación de piratas marginados.",
    año: 1997,
    volumenes: 104,
    autor: "Eiichiro Oda",
    foto_portada: "/images/portadas/manga_1.jpg",
    foto_fondo: "/images/fondos/banner_1.jpg",
    foto_logo: "/images/logos/logo_1.png",
    amazon_link: "https://www.amazon.es/One-Piece-Eiichiro-Oda/dp/8468471941",
    fecha_publicacion: "2022-12-15"
  },
  {
    id: 2,
    titulo: "Naruto",
    sinopsis: "Naruto Uzumaki, un joven ninja con el espíritu del Zorro de Nueve Colas sellado dentro de él, aspira a convertirse en el Hokage, el líder ninja de su aldea.",
    año: 1999,
    volumenes: 72,
    autor: "Masashi Kishimoto",
    foto_portada: "/images/portadas/manga_2.jpg",
    foto_fondo: "/images/fondos/banner_2.jpg",
    foto_logo: "/images/logos/logo_2.png",
    amazon_link: "https://www.amazon.es/Naruto-Masashi-Kishimoto/dp/8484496767",
    fecha_publicacion: "2022-10-20"
  },
  {
    id: 3,
    titulo: "Attack on Titan",
    sinopsis: "En un mundo donde la humanidad vive dentro de ciudades rodeadas por enormes muros que los protegen de los gigantescos Titanes, Eren Yeager jura vengarse después de que un Titán causa la destrucción de su ciudad y la muerte de su madre.",
    año: 2009,
    volumenes: 34,
    autor: "Hajime Isayama",
    foto_portada: "/images/portadas/manga_3.jpg",
    foto_fondo: "/images/fondos/banner_3.jpg",
    foto_logo: "/images/logos/logo_3.png",
    amazon_link: "https://www.amazon.es/Ataque-los-Titanes-Hajime-Isayama/dp/8467917331",
    fecha_publicacion: "2023-01-05"
  },
  {
    id: 4,
    titulo: "My Hero Academia",
    sinopsis: "En un mundo donde las personas con superpoderes son comunes, un niño sin poderes sueña con convertirse en un héroe. Su vida cambia cuando conoce a su héroe favorito, quien le transmite su poder.",
    año: 2014,
    volumenes: 36,
    autor: "Kohei Horikoshi",
    foto_portada: "/images/portadas/manga_4.jpg",
    foto_fondo: "/images/fondos/banner_4.jpg",
    foto_logo: "/images/logos/logo_4.png",
    amazon_link: "https://www.amazon.es/My-Hero-Academia-Kohei-Horikoshi/dp/8416693588",
    fecha_publicacion: "2023-02-10"
  },
  {
    id: 5,
    titulo: "Dragon Ball",
    sinopsis: "Sigue las aventuras de Son Goku desde su infancia hasta la edad adulta mientras entrena en artes marciales y explora el mundo en busca de las siete esferas del dragón.",
    año: 1984,
    volumenes: 42,
    autor: "Akira Toriyama",
    foto_portada: "/images/portadas/manga_5.jpg",
    foto_fondo: "/images/fondos/banner_5.jpg",
    foto_logo: "/images/logos/logo_5.png",
    amazon_link: "https://www.amazon.es/Dragon-Ball-Akira-Toriyama/dp/8468470805",
    fecha_publicacion: "2022-09-15"
  },
  {
    id: 6,
    titulo: "Death Note",
    sinopsis: "Light Yagami, un estudiante de secundaria, descubre un cuaderno sobrenatural que le otorga el poder de matar a cualquier persona cuyo nombre escriba en él. Comienza a usar el cuaderno para eliminar criminales, pero un detective intenta detenerlo.",
    año: 2003,
    volumenes: 12,
    autor: "Tsugumi Ohba",
    foto_portada: "/images/placeholder/anime-placeholder.jpg",
    foto_fondo: "/images/fondos/banner_1.jpg",
    foto_logo: "/images/logos/logo_1.png",
    amazon_link: "https://www.amazon.es/Death-Note-Tsugumi-Ohba/dp/8484496848",
    fecha_publicacion: "2022-11-20"
  },
  {
    id: 7,
    titulo: "Demon Slayer",
    sinopsis: "Tanjiro Kamado se convierte en un cazador de demonios después de que su familia es asesinada y su hermana Nezuko es transformada en un demonio. Busca una cura para su hermana mientras lucha contra demonios poderosos.",
    año: 2016,
    volumenes: 23,
    autor: "Koyoharu Gotouge",
    foto_portada: "/images/placeholder/anime-placeholder.jpg",
    foto_fondo: "/images/fondos/banner_2.jpg",
    foto_logo: "/images/logos/logo_2.png",
    amazon_link: "https://www.amazon.es/Guardianes-noche-Koyoharu-Gotouge/dp/8467939745",
    fecha_publicacion: "2023-03-05"
  },
  {
    id: 8,
    titulo: "Fullmetal Alchemist",
    sinopsis: "Dos hermanos, Edward y Alphonse Elric, buscan la piedra filosofal para restaurar sus cuerpos después de un fallido intento de resucitar a su madre mediante la alquimia.",
    año: 2001,
    volumenes: 27,
    autor: "Hiromu Arakawa",
    foto_portada: "/images/placeholder/anime-placeholder.jpg",
    foto_fondo: "/images/fondos/banner_3.jpg",
    foto_logo: "/images/logos/logo_3.png",
    amazon_link: "https://www.amazon.es/Fullmetal-Alchemist-Hiromu-Arakawa/dp/8467913460",
    fecha_publicacion: "2022-08-15"
  },
  {
    id: 9,
    titulo: "Tokyo Ghoul",
    sinopsis: "Ken Kaneki, un estudiante universitario, sobrevive a un encuentro con un ghoul y se convierte en un híbrido humano-ghoul. Debe aprender a vivir como un ghoul mientras mantiene su humanidad.",
    año: 2011,
    volumenes: 14,
    autor: "Sui Ishida",
    foto_portada: "/images/placeholder/anime-placeholder.jpg",
    foto_fondo: "/images/fondos/banner_4.jpg",
    foto_logo: "/images/logos/logo_4.png",
    amazon_link: "https://www.amazon.es/Tokyo-Ghoul-Sui-Ishida/dp/8467917788",
    fecha_publicacion: "2022-07-20"
  },
  {
    id: 10,
    titulo: "One Punch Man",
    sinopsis: "Saitama es un superhéroe que puede derrotar a cualquier oponente con un solo golpe, pero busca un oponente digno después de aburrirse de sus batallas fáciles.",
    año: 2009,
    volumenes: 26,
    autor: "ONE",
    foto_portada: "/images/placeholder/anime-placeholder.jpg",
    foto_fondo: "/images/fondos/banner_5.jpg",
    foto_logo: "/images/logos/logo_5.png",
    amazon_link: "https://www.amazon.es/One-Punch-Man-ONE/dp/8416090130",
    fecha_publicacion: "2023-04-10"
  },
  {
    id: 11,
    titulo: "Hunter x Hunter",
    sinopsis: "Gon Freecss descubre que su padre, a quien creía muerto, es en realidad un legendario Cazador. Inspirado, Gon decide convertirse en Cazador y encontrar a su padre.",
    año: 1998,
    volumenes: 36,
    autor: "Yoshihiro Togashi",
    foto_portada: "/images/placeholder/anime-placeholder.jpg",
    foto_fondo: "/images/fondos/banner_1.jpg",
    foto_logo: "/images/logos/logo_1.png",
    amazon_link: "https://www.amazon.es/Hunter-Yoshihiro-Togashi/dp/8467476885",
    fecha_publicacion: "2022-06-15"
  },
  {
    id: 12,
    titulo: "Bleach",
    sinopsis: "Ichigo Kurosaki obtiene los poderes de un Shinigami (Dios de la Muerte) y debe proteger a los humanos de espíritus malignos y guiar a las almas al más allá.",
    año: 2001,
    volumenes: 74,
    autor: "Tite Kubo",
    foto_portada: "/images/placeholder/anime-placeholder.jpg",
    foto_fondo: "/images/fondos/banner_2.jpg",
    foto_logo: "/images/logos/logo_2.png",
    amazon_link: "https://www.amazon.es/Bleach-Tite-Kubo/dp/8416090149",
    fecha_publicacion: "2022-05-20"
  },
  {
    id: 13,
    titulo: "Jujutsu Kaisen",
    sinopsis: "Yuji Itadori, un estudiante de secundaria con habilidades físicas excepcionales, se une a una organización secreta de hechiceros para eliminar a una poderosa maldición.",
    año: 2018,
    volumenes: 19,
    autor: "Gege Akutami",
    foto_portada: "/images/placeholder/anime-placeholder.jpg",
    foto_fondo: "/images/fondos/banner_3.jpg",
    foto_logo: "/images/logos/logo_3.png",
    amazon_link: "https://www.amazon.es/Jujutsu-Kaisen-Gege-Akutami/dp/8467939850",
    fecha_publicacion: "2023-05-05"
  },
  {
    id: 14,
    titulo: "Chainsaw Man",
    sinopsis: "Denji, un joven que puede transformarse en el 'Chainsaw Man' fusionándose con su demonio mascota Pochita, se une a los Cazadores de Demonios para pagar sus deudas y llevar una vida normal.",
    año: 2018,
    volumenes: 11,
    autor: "Tatsuki Fujimoto",
    foto_portada: "/images/placeholder/anime-placeholder.jpg",
    foto_fondo: "/images/fondos/banner_4.jpg",
    foto_logo: "/images/logos/logo_4.png",
    amazon_link: "https://www.amazon.es/Chainsaw-Man-Tatsuki-Fujimoto/dp/8467940751",
    fecha_publicacion: "2023-06-10"
  },
  {
    id: 15,
    titulo: "Spy x Family",
    sinopsis: "Un espía, un asesino y una telépata forman una familia mientras ocultan sus identidades entre sí para llevar a cabo una misión que podría determinar el destino del mundo.",
    año: 2019,
    volumenes: 9,
    autor: "Tatsuya Endo",
    foto_portada: "/images/placeholder/anime-placeholder.jpg",
    foto_fondo: "/images/fondos/banner_5.jpg",
    foto_logo: "/images/logos/logo_5.png",
    amazon_link: "https://www.amazon.es/Spy-Family-Tatsuya-Endo/dp/8467941472",
    fecha_publicacion: "2023-07-15"
  }
];

export default mangasData;
